### ISSUE TITLE
⚙️ Automatisches erstellen von @democracy-deutschland/ui NPM packages

### ISSUE THREAD

**Issue by ManAnRuck** [demokratie-live/democracy-ui#4]
Der Prozess neue NPM Packages zu erstellen, kann und sollte automatisiert werden um die DE (Developer Expirience) zu verbessern und Zeit zu sparen.

## ❓ Offene fragen

- [ ] Wie wird die richtige Variante, Major, Minor oder Patch, ausgewählt?
- [ ] Kann dies mithilfe von Chromatic umgesetzt werden

## 🧾 Subtasks

- [ ] Check ESLint & TypeScript
- [ ] Bei einem **PR** neue alpha Versionen erstellen
  - [ ] x.x.x-ISSUE_NUMBER-VORTLAUFENDE_NUMMER
- [ ] Bei einem **push** auf **develop** 
  - [ ] x.x.x-rc.VORTLAUFENDE_NUMMER
- [ ] Bei einem **push** auf **master**
  - [ ] x.x.x
- [ ] Version in der **package.json** sollte entsprechend aktualisiert werden
